language: node_js

node_js:
  - 5
  - 6

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
