environment:
  matrix:
    - nodejs_version: 4.2

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm@next
  - node_modules\.bin\npm install

test_script:
  - node_modules\.bin\npm run test

build: off

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
